  stop        Stop services
  top         Display the running processes
  unpause     Unpause services
  up          Create and start containers
  version     Show the Docker Compose version information
  wait        Block until the first service container stops
  watch       Watch build context for service and rebuild/refresh containers when files are updated

Run 'docker compose COMMAND --help' for more information on a command.
unknown docker command: "compose exect"

(venv) D:\project-django\achreh>docker-compose exec backend pytrhon manage.py createsuperuser  
time="2024-12-15T21:36:40+03:30" level=warning msg="D:\\project-django\\achreh\\docker-compose.yaml: `version` is obsolete"
OCI runtime exec failed: exec failed: unable to start container process: exec: "pytrhon": executable file not found in $PATH: unknown

(venv) D:\project-django\achreh>docker-compose exec backend python manage.py createsuperuser  
time="2024-12-15T21:36:54+03:30" level=warning msg="D:\\project-django\\achreh\\docker-compose.yaml: `version` is obsolete"
Mobile: 0901234567 
Password: 
Password (again):
This password is too short. It must contain at least 8 characters.
This password is too common.
This password is entirely numeric.
Bypass password validation and create user anyway? [y/N]: y
Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 90, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 239, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(
  File "/app/apps/user/models.py", line 16, in create_superuser
    return self.create_user(mobile, password, **extra_fields)
  File "/app/apps/user/models.py", line 8, in create_user
    user = self.model(mobile=mobile, **extra_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: CustomUser() got unexpected keyword arguments: 'is_superuser'
